baseURL = 'https://avavani.github.io/atlas/'
languageCode = 'en-us'
title = 'Atlas'
theme = 'Ardeidae'

[markup.goldmark.renderer]
  unsafe = true

  [security]
  enableInlineShortcodes = true

  [params]
  description = "Hi, I'm Avani, and here, I map the world"
  image = "/images/header.png"